name: build and publish mybricks-pcspa
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check commit message
        id: check_commit
        run: echo "::set-output name=message::$(git log -1 --pretty=format:'%B')"

      - name: Run CI based on commit message
        run: |
          commit_message="${{ steps.commit.outputs.message }}"
          if [[ $commit_message == *"ci serviceUpdate"* ]]; then
            echo "编译带服务器更新的app"
            npm run publishToNpm:serviceUpdate
          elif [[ $commit_message == *"ci"* ]]; then
            echo "编译不带服务器更新的app"
            npm run publishToNpm
          else
            echo "No specific action triggered."
          fi
