name: build and publish mybricks-pcspa
on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check commit message
        id: check_commit
        run: echo "commit_message=$(git log -1 --pretty=format:'%B')" >> $GITHUB_ENV

      - name: Run CI based on commit message
        run: |
          if [[ $commit_message == *"ci serviceUpdate"* ]]; then
            echo "编译带服务器更新的app"
            npm run publishToNpm:serviceUpdate
          elif [[ $commit_message == *"ci"* ]]; then
            echo "编译不带服务器更新的app"
            npm run publishToNpm
          else
            echo "没有发现CI打包的命令"
          fi
